### ISSUE TITLE
Not compatible with latest database cookbook

### ISSUE THREAD

**Issue by martinb3** [cybermerc/percona_multi#3]
We probably need a unit test for this on stack_commons, as it appears that just loading percona and mysql cookbooks together can cause this issue.

@jujugrrr said in https://github.com/AutomationSupport/magentostack/pull/84:

It seems somehow the backtick don't work, so : 

```
GRANT usage,select,lock tables,show view,reload,super ON `*`.* TO 'magento_user'@'10.0.2.15' IDENTIFIED BY 'magento_password';
ERROR 1221 (HY000): Incorrect usage of DB GRANT and GLOBAL PRIVILEGES

```

is failing.
However 

```
GRANT usage,select,lock tables,show view,reload,super ON *.* TO 'magento_user'@'10.0.2.15' IDENTIFIED BY 'magento_password';
Query OK, 0 rows affected (0.00 sec)
```

is all fine. 

Not sure to understand why it's been introduced by the last database cookbook release, as the backtick have always been there.

It's related to `super` and `reload` privileges only.

```
mysql> GRANT super ON `*`.* TO 'magento_user'@'10.0.2.15';
ERROR 1221 (HY000): Incorrect usage of DB GRANT and GLOBAL PRIVILEGES
mysql> GRANT super ON *.* TO 'magento_user'@'10.0.2.15';
Query OK, 0 rows affected (0.00 sec)
```

Super should only be applied on `*.*` it seems,  so it should work, but somehow :  

```
`*`.*
```

 is interpreted differently than

```
*.*
```

@cybermerc Does it sound familiar to you? @martinb3 told me you had more experience with the database cookbook

**Comment by martinb3** [comment]
Here's the error in a grant I'm seeing:

```
         * mysql_database_user[global grants on node[community-centos-65]] action grant[2015-01-20T13:18:01+00:00] INFO: Processing mysql_database_user[global grants on node[community-centos-65]] action grant (stack_commons::mysql_base line 186)
       [2015-01-20T13:18:01+00:00] INFO: mysql_database_user[global grants on node[community-centos-65]]: granting access with statement [GRANT usage,select,lock tables,show view,reload,super ON `*`.* TO 'magento_user'@'10.0.2.15' IDENTIFIED BY 'magento_password']
       [2015-01-20T13:18:01+00:00] INFO: Retrying execution of mysql_database_user[global grants on node[community-centos-65]], 1 attempt(s) left
       [2015-01-20T13:18:03+00:00] INFO: mysql_database_user[global grants on node[community-centos-65]]: granting access with statement [GRANT usage,select,lock tables,show view,reload,super ON `*`.* TO 'magento_user'@'10.0.2.15' IDENTIFIED BY 'magento_password']
       [2015-01-20T13:18:03+00:00] INFO: Retrying execution of mysql_database_user[global grants on node[community-centos-65]], 0 attempt(s) left
       [2015-01-20T13:18:05+00:00] INFO: mysql_database_user[global grants on node[community-centos-65]]: granting access with statement [GRANT usage,select,lock tables,show view,reload,super ON `*`.* TO 'magento_user'@'10.0.2.15' IDENTIFIED BY 'magento_password']


           ================================================================================
           Error executing action `grant` on resource 'mysql_database_user[global grants on node[community-centos-65]]'
           ================================================================================


           Mysql2::Error
           -------------
           Incorrect usage of DB GRANT and GLOBAL PRIVILEGES

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/database/libraries/provider_database_mysql_user.rb:140:in `query'
           /tmp/kitchen/cache/cookbooks/database/libraries/provider_database_mysql_user.rb:140:in `block (2 levels) in <class:MysqlUser>'
           /tmp/kitchen/cache/cookbooks/database/libraries/provider_database_mysql_user.rb:131:in `block in <class:MysqlUser>'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/stack_commons/recipes/mysql_base.rb

           186:     mysql_database_user "global grants on #{app_node}" do
           187:       username database_opts['mysql_user']
           188:       connection connection_info
           189:       password database_opts['mysql_password']
           190:       host best_ip_for(app_node)
           191:       privileges database_opts['global_privileges']
           192:       retries 2
           193:       retry_delay 2
           194:       action %w(create grant)
           195:       only_if { database_opts['global_privileges'] && !database_opts['global_privileges'].empty? }
           196:     end
           197:   end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/stack_commons/recipes/mysql_base.rb:186:in `block (2 levels) in from_file'

           mysql_database_user("global grants on node[community-centos-65]") do
             provider Chef::Provider::Database::MysqlUser
             action [:create, :grant]
             updated true
             retries 0
             retry_delay 2
             guard_interpreter :default
             username "magento_user"
             host "10.0.2.15"
             privileges [:usage, :select, :"lock tables", :"show view", :reload, :super]
             cookbook_name "stack_commons"
             recipe_name "mysql_base"
             connection {:host=>"localhost", :username=>"root", :password=>"randompass"}
             password "magento_password"
             only_if { #code block }
           end

```

**Comment by martinb3** [comment]
This appears to be a bug in the database cookbook, not specific to percona. Closing this.
